site_name: Notes
site_description: Personal knowledge base
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
plugins:
  - search
  - roamlinks
  - mermaid2
docs_dir: '.'
exclude_docs: |
  .git/
  .github/
  .obsidian/
  site/