# MkDocs GitHub Pages Deployment Workflow

name: Deploy MkDocs to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install MkDocs and required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin
          pip install mkdocs-mermaid2-plugin

      # Create mkdocs.yml if it doesn't exist
      - name: Create MkDocs config
        run: |
          if [ ! -f mkdocs.yml ]; then
            cat > mkdocs.yml << EOF
            site_name: Notes
            site_description: Personal knowledge base
            theme:
              name: material
              palette:
                primary: indigo
                accent: indigo
              features:
                - navigation.instant
                - navigation.tracking
                - navigation.expand
                - navigation.indexes
                - content.code.copy
            markdown_extensions:
              - pymdownx.highlight
              - pymdownx.superfences
              - pymdownx.tasklist
              - pymdownx.emoji
              - admonition
              - toc:
                  permalink: true
            plugins:
              - search
              - roamlinks
              - mermaid2
            docs_dir: '.'
            exclude_docs: |
              .git/
              .github/
              .obsidian/
              site/
            EOF
          fi

      # Build the MkDocs site
      - name: Build site
        run: mkdocs build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
